version: '3.8'

services:
  database:
    image: mysql:8.0
    container_name: mysql_db
    restart: on-failure:3
    environment:
      MYSQL_ROOT_PASSWORD: tset123
      MYSQL_DATABASE: boutique_hotel
      MYSQL_USER: application_user
      MYSQL_PASSWORD: sadf123
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:

