openapi: 3.0.0
info:
  title: HotelBookingAPI
  description: API for managing hotel bookings and room availability
  version: 1.0.0
servers:
  - url: /hotelBooking
paths:
  /booking:
    post:
      summary: Create a new booking
      description: |
        Creates a new booking with the provided details.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                surname:
                  type: string
                email:
                  type: string
                breakfast:
                    type: boolean
                startDate:
                  type: string
                  format: date
                duration:
                  type: integer
                roomSelection:
                  type: string
              required:
                - name
                - surname
                - email
                - emailConfirmed
                - breakfast
                - startDate
                - duration
                - roomSelection
      responses:
        '200':
          description: Booking created successfully
        '400':
          description: Invalid request parameters or missing required parameters
  /checkRoomAvailability:
    get:
      summary: Check room availability
      description: |
        Checks the availability of a room for the specified duration.
      parameters:
        - name: roomNumber
          in: query
          description: Room number to check availability for
          required: true
          schema:
            type: integer
        - name: startDate
          in: query
          description: Start date of the booking
          required: true
          schema:
            type: string
            format: date
        - name: duration
          in: query
          description: Duration of the booking in days
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Room availability checked successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  available:
                    type: boolean
  /getAllRooms:
    get:
      summary: Get all rooms
      description: |
        Retrieves an overview of all available rooms.
      responses:
        '200':
          description: Overview of all rooms retrieved successfully
